on:
  push:
    branches:
      - staging

concurrency:
  group: openfn-deployment
  cancel-in-progress: false

jobs:
  deploy-to-lightning:
    runs-on: ubuntu-latest
    name: A job to deploy to Lightning
    permissions:
      contents: write
    steps:
      - name: openfn deploy
        uses: openfn/cli-deploy-action@v1.0.0
        with:
          secret_input: ${{ secrets.OPENFN_cd92dd57_9a3c_4318_bdcb_f57a386cf811_API_KEY }}
          config_path_input: 'openfn-cd92dd57-9a3c-4318-bdcb-f57a386cf811-config.json'
